---
title: "Poisson-Normal, one parameter"
author: 
- "Subhash Lele"
- "C George Glen"
- "Jose Miguel Ponciano"
date: "`r Sys.Date()`"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Poisson Normal model, one parameter
First we upload the necessary function libraries
```{r message=FALSE}
#### ---------------------------------------------------------------------------
#### Load functions
source("TestingLaplaceToolkit4.0.R")
source("TestingLaplaceTMB.functions7.0.R") 
source("TestingLaplaceTMB.models2.0.R") 

#### ---------------------------------------------------------------------------
#### Load libraries
library(ggplot2)
library(patchwork)
library(knitr)
library(boot)
```

a) Comparison of the the MC likelihood function with TMB
```{r }


#### ---------------------------------------------------------------------------
parms.err.varsPN <- list(beta=-1, df1=2, sd1=3)
out.simPN <- sim.example(n=100, parm.list=parms.err.varsPN, model="Pois.Norm")




#### ---------------------------------------------------------------------------
ModPN.dc.beta <- onedcfitrun(model="Pois.Norm", true.parms=parms.err.varsPN,
                             sim.data = out.simPN,n.iter=50000,n.adapt=1000,
                             n.update=10000, thin=5, n.chains=5, clones.seq=8)

Beta.hat <- summary(ModPN.dc.beta)[[1]][1]
print(Beta.hat)
do.call(rbind, ModPN.dc.beta) |> mean()



#### ---------------------------------------------------------------------------
# Wald-tyep CI's 
Beta.hatPN.CI <- confint(ModPN.dc.beta)

c(mean( do.call(rbind, ModPN.dc.beta) ) - 1.96*sqrt( 32*var(do.call(rbind, ModPN.dc.beta)) ),
  mean( do.call(rbind, ModPN.dc.beta) ) + 1.96*sqrt( 32*var(do.call(rbind, ModPN.dc.beta)) )
)
Beta.hatPN.CI



#### ---------------------------------------------------------------------------
# True (assuming all other parms known) profile likelihood for beta using Monte Carlo
MCprof.ModPN <- MCprofile1d(B=300000, parm.list=parms.err.varsPN,sim.data=out.simPN, 
                            bracket=2, prec.prof=0.01, model="Pois.Norm",
                            plot.it=FALSE, overlay=FALSE)



#### ---------------------------------------------------------------------------
# LOESS smoothing of MC profile
psi.grid <-  seq(Beta.hat-1.9,Beta.hat+1.8,0.01)
MCdataPN <- data.frame(beta_values=MCprof.ModPN[,1],RelPL=MCprof.ModPN[,2])
tmp <- loess(RelPL ~ beta_values,data=MCdataPN, span=0.08)
newdata.Mod <- data.frame(beta_values=psi.grid)
MCprof.smooth <- predict(tmp,newdata=newdata.Mod)
where.nas <- which(is.na(MCprof.smooth), arr.ind=TRUE)
if(length(where.nas)>0){
  MCprof4plot <- MCprof.smooth[-where.nas]/max(MCprof.smooth[-where.nas])
  psi.grid4plot <- psi.grid[-where.nas]
  #MCprof4plot <- MCprof.smooth/max(MCprof.smooth)
}else{
  MCprof4plot <- MCprof.smooth/max(MCprof.smooth)
  psi.grid4plot <- psi.grid
}

## saving the ggplot object:
gridmcdf <- data.frame(Beta.values=psi.grid4plot, Rel.Prof.Like=MCprof4plot)

#### ---------------------------------------------------------------------------
# TMB profile likelihood
parms4tmb <- list(beta=parms.err.varsPN$beta, df1=parms.err.varsPN$df1,
                  lnsd1 = log(parms.err.varsPN$sd1))
testPN <- run.tmb(profile.par.name="beta", profile.par=MCprof.ModPN[,1], 
                  known.parm=parms4tmb, sim.data=out.simPN, 
                  model="Pois.Norm")
plot(testPN$prof$param, testPN$prof$rel.like, type="l")
abline(v=testPN$MLres$opt.ML$par)



#### ---------------------------------------------------------------------------
# Now computing the TMB profile:
# Plot the MC profile with the TMB profile
PN1 <- ggplot(gridmcdf, aes(Beta.values, Rel.Prof.Like) ) + 
  geom_line(linewidth=1, aes(linetype ="black.line"), color="black") + xlim( c(-3,1) ) +
  labs( x=bquote("Values of" ~ beta), y="Relative Likelihood", title = "A") +
  geom_line(data = testPN, aes( x=param, y=rel.like, linetype="red.line"), color = "red", linewidth=1) +
  
  geom_line(data=data.frame(x=as.vector(Beta.hatPN.CI), y=c(0,0)), aes(x=x,y=y, linetype = "blue.line"), color = "blue", linewidth=2)+
  geom_vline(linetype="dotted",linewidth=0.95, mapping = aes(linetype = "black.line2", xintercept = Beta.hat), color = "black")+
  
  geom_hline(linetype="dotted",linewidth=0.9, mapping = aes(linetype="gray.line", yintercept = exp(-qchisq(p=0.95,df=1)/2)), color = "gray")+ 
  scale_linetype_manual(name = "", values = c(red.line = 2, black.line = 1, blue.line = 1, black.line2 = 1, gray.line =2), 
                        labels = c(red.line = "TMB", black.line = "MC", blue.line = "DC-CI", black.line2 = "MLE", gray.line = bquote("exp(-0.5"~ chi[0.95]^2~")")), 
                        limits = c("red.line", "black.line", "blue.line", "black.line2", "gray.line"), 
                        guide = guide_legend(override.aes = list(color = c("red", "black", "blue", "black", "gray"), linetype = c("dotted","solid","solid",    "dotted","dotted"), linewidth = c(1, 1,1, 1,1) )) ) +
  theme_classic() + 
  theme(text = element_text(size=15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.ticks.length=unit(0.2, "cm"), legend.position = "bottom") 





```

b) Comparison of the the MC likelihood function with GT


```{r}
new.par.listPN <- parms.err.varsPN
new.par.listPN$beta <- Beta.hat


#### ---------------------------------------------------------------------------
# Sampling from f(X|(Y,W))
Xpost.ModPN <- Xpost.samp(model="Pois.Norm", parm.list=new.par.listPN,
                         sim.data=out.simPN, n.iter=51000,n.adapt=1000,
                         n.update=1000,thin=5,n.chains=5)

Xpost.binned <- do.call(rbind,Xpost.ModPN)



#### ---------------------------------------------------------------------------
# Running the GT algorithm
ModelPN.GTprof <- GT.prof(model="Pois.Norm", parm.list=new.par.listPN,sim.data=out.simPN,
        XpostSample=Xpost.binned, bracket=2, prec.prof=0.01,
        plot.it=FALSE, overlay=TRUE,mycol="blue",
        dotted=1)




#### ---------------------------------------------------------------------------
### Save files for plots
OP.PNmc       <- gridmcdf
OP.PNtmb      <- testPN
OP.PNgt       <- data.frame(ModelPN.GTprof)
OP.PNDCwaldCI <- data.frame(x=as.vector(Beta.hatPN.CI))
# save(parms.err.varsPN, new.par.listPN, out.simPN,OP.PNmc, OP.PNtmb, OP.PNgt, OP.PNgt, OP.PNDCwaldCI, file="PN-OnePar_plotdata.RData")
# save.image( file="PN-OnePar_image.RData" )






#### ---------------------------------------------------------------------------
# Plotting the MC profile with the GT profile
PN2 <- ggplot(gridmcdf, aes(Beta.values, Rel.Prof.Like) ) + 
  geom_line(linewidth=1, aes(linetype ="black.line"), color="black") + xlim( c(-3,1) ) +
  labs( x=bquote("Values of" ~ beta), y="Relative Likelihood", title = "B") +
  geom_line(data = data.frame(ModelPN.GTprof), aes( x=beta.profs, y=rel.prof, linetype="red.line"), color = "red", linewidth=1) +
  
  geom_line(data=data.frame(x=as.vector(Beta.hatPN.CI), y=c(0,0)), aes(x=x,y=y, linetype = "blue.line"), color = "blue", linewidth=2)+
  geom_vline(linetype="dotted",linewidth=0.95, mapping = aes(linetype = "black.line2", xintercept = Beta.hat), color = "black")+
  
  geom_hline(linetype="dotted",linewidth=0.9, mapping = aes(linetype="gray.line", yintercept = exp(-qchisq(p=0.95,df=1)/2)), color = "gray")+ 
  scale_linetype_manual(name = "", values = c(red.line = 2, black.line = 1, blue.line = 1, black.line2 = 1, gray.line =2), 
                        labels = c(red.line = "GT", black.line = "MC", blue.line = "DC-CI", black.line2 = "MLE", gray.line = bquote("exp(-0.5"~ chi[0.95]^2~")")), 
                        limits = c("red.line", "black.line", "blue.line", "black.line2", "gray.line"), 
                        guide = guide_legend(override.aes = list(color = c("red", "black", "blue", "black", "gray"), linetype = c("dotted","solid","solid",    "dotted","dotted"), linewidth = c(1, 1,1, 1,1) )) ) +
  theme_classic() + 
  theme(text = element_text(size=15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.ticks.length=unit(0.2, "cm"), legend.position = "bottom")   







#### ---------------------------------------------------------------------------
PN.all <- ggplot(gridmcdf, aes(Beta.values, Rel.Prof.Like) ) + 
  geom_line(linewidth=1, aes(linetype ="black.line"), color="black") + xlim( c(-2,-0.25) ) +
  labs( x=bquote("Values of" ~ beta), y="Relative Likelihood", title = "") +
  geom_line(data = testPN, aes( x=param, y=rel.like, linetype="red.line"), color = "black", linewidth=1) +
  geom_line(data = data.frame(ModelPN.GTprof), aes( x=beta.profs, y=rel.prof, linetype="anothered.line"), color = "black", linewidth=1) +
  
  geom_line(data=data.frame(x=as.vector(Beta.hatPN.CI), y=c(0,0)), aes(x=x,y=y, linetype = "blue.line"), color = "black", linewidth=2)+
  geom_vline(linetype=5,linewidth=0.95, mapping = aes(linetype = "black.line2", xintercept = -1.031482), color = "black")+
  
  geom_hline(linetype=6,linewidth=0.9, mapping = aes(linetype="gray.line", yintercept = exp(-qchisq(p=0.95,df=1)/2)), color = "black")+ 
  scale_linetype_manual(name = "", values = c(red.line = 4, anothered.line=2, black.line = 3, blue.line = 1, black.line2 = 5, gray.line =6), 
                        labels = c(red.line = "TMB", anothered.line="GT", black.line = "MC", blue.line = "DC-CI", black.line2 = "MLE", gray.line = bquote("exp(-0.5"~ chi[0.95]^2~")")), 
                        limits = c("red.line","anothered.line" ,"black.line", "blue.line", "black.line2", "gray.line"), 
                        guide = guide_legend(override.aes = list(color = rep("black",6), linetype = c(4,2,3,1,5,6), linewidth = c(1,1,1, 2,1,1) )) ) +
  theme_classic() + 
  theme(text = element_text(size=15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        legend.key.width = unit(4, "line"),        
        axis.ticks.length=unit(0.2, "cm"), legend.position = "bottom")   


# save(PN1,file="PN1v2.RData")
# save(PN2,file="PN2v2.RData")
# save(PN.all,file="PNall.RData")  
# save.image("PN-Onepar.RData")

```



Remove previous object file and DLL if present
```{r}
#### ---------------------------------------------------------------------------
dyn.unload(dynlib(model_name))

if (length(list.files(pattern = "\\.o$", full.names = TRUE))>0) {
  file.remove(list.files(pattern = "\\.o$", full.names = TRUE))
}
if (length(list.files(pattern = "\\.so$", full.names = TRUE))>0) {
  file.remove(list.files(pattern = "\\.so$", full.names = TRUE))
}
if (length(list.files(pattern = "\\.cpp$", full.names = TRUE))>0) {
  file.remove(list.files(pattern = "\\.cpp$", full.names = TRUE))
}
#
```
